version: '3.8'
services:
  client:
    image: rocdanesabi/tfe-master:client
    ports:
      - '12735:12735'
    networks:
      - tfe-master
  data-center:
    image: rocdanesabi/tfe-master:datacenter
    command: sh -c "chmod +x tmp/db.sh && ./tmp/db.sh"
    ports:
      - '25432:5432'
    networks:
      - tfe-master
    environment:
      - POSTGRES_USER=loga
      - POSTGRES_PASSWORD=Log@2020
      - POSTGRES_DB=loga
    restart: always
  data-warehouse:
    image: rocdanesabi/tfe-master:datawarehouse
    ports:
      - '35432:5432'
    networks:
      - tfe-master
    environment:
      - POSTGRES_USER=loga-dwh
      - POSTGRES_PASSWORD=Log@2020
      - POSTGRES_DB=loga-dwh
    restart: always
  authentication-service:
    image: rocdanesabi/tfe-master:authentication-service
    ports:
      - "8001:8001"
    networks:
      - tfe-master
    depends_on:
      - naming-service
      - data-center
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  customer-service:
    image: rocdanesabi/tfe-master:customer-service
    ports:
      - "8002:8002"
    networks:
      - tfe-master
    depends_on:
      - naming-service
      - data-center
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  maintenance-service:
    image: rocdanesabi/tfe-master:maintenance-service
    ports:
      - "8003:8003"
    networks:
      - tfe-master
    depends_on:
      - naming-service
      - data-center
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  monitoring-service:
    image: rocdanesabi/tfe-master:monitoring-service
    ports:
      - "8004:8004"
    networks:
      - tfe-master
    depends_on:
      - naming-service
      - data-warehouse
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  intelligent-service:
    image: rocdanesabi/tfe-master:intelligent-service
    ports:
      - "8005:8005"
    networks:
      - tfe-master
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  report-service:
    image: rocdanesabi/tfe-master:report-service
    ports:
      - "8006:8006"
    networks:
      - tfe-master
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  gateway-service:
    image: rocdanesabi/tfe-master:gateway-service
    ports:
      - "8765:8765"
    networks:
      - tfe-master
    depends_on:
      - naming-service
    environment:
      EUREKA.CLIENT.SERVICEURL.DEFAULTZONE: http://naming-service:8761/eureka
      MANAGEMENT.ZIPKIN.TRACING.ENDPOINT: http://distributed-tracing:9411/api/v2/spans
  naming-service:
    image: rocdanesabi/tfe-master:naming-service
    ports:
      - "8761:8761"
    networks:
      - tfe-master
  distributed-tracing:
    image: rocdanesabi/tfe-master:distributed-tracing
    ports:
      - "9411:9411"
    networks:
      - tfe-master
    restart: always
networks:
  tfe-master:
